# Input/Output paths
input_dir: "/path/to/fastqs"
reference: "/path/to/resources/reference/GCF_000069185.1_ASM6918v1_genomic.fna.gz" #need to be the name of the file
output: "/path/to/output"

# Kraken2 database path
kraken2_db: "/orange/bphl-florida/databases/kraken_databases/minikraken2_v2_8GB_201904_UPDATE"


# NTM-profiler database path
NTM_profiler_db: "/path/to/resources/NTM-profiler"

# HMM database path
erm41: "/path/to/resources/hmm/erm41_cds.fasta"

card_database: "/path/to/resources/carddatabase/card_db"


# For BPHL use: /blue/bphl-florida/share/keywest_database/resources